### ISSUE TITLE
Update Role to work with Ubuntu 22.04 Rocky Linux 9

### ISSUE THREAD

**Issue by JulianHn** [ome/ansible-role-ice#22]
Just to avoid multiple people taking the same role to update (cf. https://github.com/ome/omero-server-docker/issues/79 / https://github.com/ome/omero-web-docker/issues/74) I am opening an issue here, so people can claim that specific role to work on.

**Comment by manics** [comment]
I've got a Ubuntu 22.04 Ice 3.6 Docker build for amd64 and arm64/aarch64 in https://github.com/manics/omero-ice-docker
If it's useful feel free to copy those artifacts out of the Docker image, or if you'd like to be added as a maintainer, or have it transferred to an org, just let me know!

**Comment by jburel** [comment]
see https://github.com/ome/ansible-role-ice/pull/23
